### PR TITLE
Password confirmation bug

### LINKED ISSUE #56: Password Confirmation
Password confirmation is not working.

### PR DESCRIPTION
**Pull request by AngelaGuardia**
closes #56 

Fixes bugs related to password confirmation.

Please review the comments I added to this PR - would love to hear your thoughts on them.

### CODE REVIEW

File: app/controllers/users_controller.rb [hunk 1]
```diff
@@ -10,11 +10,10 @@ def create
       flash[:notice] = "You are now registered and logged in."
       redirect_to '/profile'
     else
-      flash[:notice] = @user.errors.full_messages.to_sentence
+      flash[:notice] = @user.errors.full_messages.uniq.to_sentence
```
Comment (AngelaGuardia) [inline app/controllers/users_controller.rb:13]: Added that uniq method there because the password confirmation gave me two repeated errors. Seems like a bit of a bandaid so if anyone has ideas as to why I was getting duplicate errors please let me know!

My best guess is that maybe it's checking the confirmation both ways:
password == password_confirmation
password_confirmation == password

That's just a guess though. Really unsure why it's behaving that way.

File: app/models/user.rb [hunk 2]
```diff
@@ -1,13 +1,7 @@
 class User < ApplicationRecord
   validates :email, uniqueness: true, presence: true
+  validates :password, confirmation: true, presence: true
   validates_presence_of :address, :city, :state, :zip, :password, :name
```
Comment (AngelaGuardia) [inline app/models/user.rb:4]: I decided not to validate the presence of password_confirmation here. It seemed redundant since we're validating the confirmation so in order for that to pass the password_confirmation must be present. Open to thoughts on that!

File: app/controllers/users_controller.rb (hunk 1 above)
Comment (KieraAllen) [reply app/controllers/users_controller.rb:13]: I think `.uniq` is a smart fix for now. Not sure about the duplicate errors... I'm researching the docs to get a better handle on password confirmation.

File: app/models/user.rb (hunk 2 above)
Comment (KieraAllen) [reply app/models/user.rb:4]: So, instead of `validates :password_confirmation` you just included a `:true` confirmation along with the password validation? That makes sense to me!

**Review by KieraAllen — APPROVED** [review]

File: app/models/user.rb (hunk 2 above)
Comment (AngelaGuardia) [reply app/models/user.rb:4]: That's right!

File: app/controllers/users_controller.rb (hunk 1 above)
Comment (lkriffell) [reply app/controllers/users_controller.rb:13]: I saw those duplicate errors and couldn't pinpoint why it was doing that so I'm glad this works.

File: app/models/user.rb (hunk 2 above)
Comment (lkriffell) [reply app/models/user.rb:4]: Nice! I was experimenting with combining different validations to see what it would give me. I'm glad the solution was simple

**Review by lkriffell — APPROVED** [review]

File: app/controllers/users_controller.rb (hunk 1 above)
Comment (Arique1104) [reply app/controllers/users_controller.rb:13]: That's interesting.  In an unrelated note, do you think it's because we've named all our flash notices flash[:notice]?  I don't think this suggestion would fix the duplication errors, but I do believe that we wouldn't really know how to pin point it if the flash notice has the same name?  I'm wondering what the pro/cons are for naming all our flash notices this way?

I agree with everyone else, @AngelaGuardia, this seems like a good enough fix for now.

**Review by Arique1104 — APPROVED** [review]
This looks good to me.
